// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Copies the specification's `common_types.json` into Dart source, so the
/// published package carries the shared type definitions instead of asking
/// every caller to supply them.
///
/// Run from the package directory after editing the specification:
///
/// ```sh
/// dart run tool/generate_common_types.dart
/// ```
///
/// `test/common_types_test.dart` fails if the checked-in output has drifted
/// from the specification.
library;

import 'dart:io';

/// The specification file to copy, relative to the repository root.
const String source = 'specification/v0_9/json/common_types.json';

/// The file to write, relative to the package directory.
const String output = 'lib/src/validation/common_types.g.dart';

void main() {
  final String json = readSource();
  File(output).writeAsStringSync(render(json));
  stdout.writeln('Wrote $output from $source.');
}

/// Reads [source], searching upwards for the repository root so the tool runs
/// from the package directory or the workspace root.
String readSource() {
  Directory dir = Directory.current;
  while (true) {
    final candidate = File('${dir.path}/$source');
    if (candidate.existsSync()) return candidate.readAsStringSync();
    final Directory parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError(
        'Could not find $source above ${Directory.current.path}.',
      );
    }
    dir = parent;
  }
}

/// Wraps [json] in a Dart library, verbatim, so the generated file diffs
/// against the specification one line at a time.
///
/// The document is embedded as a raw multiline string, which reproduces `$`
/// and `\` without escaping. Throws if [json] is not expressible that way, so
/// a specification edit cannot silently produce a file that says something
/// other than what it copied.
String render(String json) {
  if (json.contains("'''")) {
    throw StateError("$source contains ''', which ends the string literal.");
  }
  if (json.endsWith("'")) {
    throw StateError("$source ends with ', which extends the delimiter.");
  }
  if (!json.startsWith('{')) {
    throw StateError('$source does not start with a JSON object.');
  }
  return '''
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by tool/generate_common_types.dart. Do not edit by hand.
//
// A verbatim copy of $source.

/// The `common_types.json` document for protocol v0.9, as published.
const String commonTypesV0_9Json = r\'\'\'
$json\'\'\';
''';
}
