# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: a2ui_core
description: Core package for A2UI protocol.
repository: https://github.com/a2ui-project/a2ui/tree/main/dart/a2ui_core
version: 0.2.0

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  json_schema_builder: ^0.1.7
  meta: ^1.17.0
  preact_signals: ^1.9.4

dev_dependencies:
  path: ^1.9.0
  test: ^1.26.2
  yaml: ^3.1.2
